
services:
  - type: web
    name: chat-app-server
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DB_URI
        fromDatabase:
          name: chat-app-db
          property: connectionString
      - key: ORIGIN
        fromService:
          type: web
          name: chat-app-client
          property: url
  - type: web
    name: chat-app-client
    plan: free
    region: oregon
    env: static
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "client/dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: chat-app-db
    plan: free
